GEMINI_API_KEY = "AIzaSyCD_5d3r7nRyn4H4eZ58YzqHh8LOLrePTo"
EMAIL_USER = "italofariaspcd@gmail.com"
EMAIL_PASSWORD = "vbrk irry dmaf onwc"
EMAIL_DESTINATARIO = "italofariaspcd@gmail.com"
spreadsheet = "https://docs.google.com/spreadsheets/d/18Ky7xrNGrVKbmbhPLv8DVHYYFAinr1UO9iqWXyNFWgk/edit?gid=0#gid=0"

[email]
usuario = "zequinhadaesquinase@gmail.com"
senha = "ymnz awtd eiyf tfhi"
destinatario = "zequinhadaesquinase@gmail.com""